name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
    
    - name: Test build
      run: |
        # Basic file existence check
        test -f dist/sketch-widget.min.js
        test -f dist/sketch-widget.min.js.map
        
        # Check file size (should be reasonable)
        size=$(stat -c%s dist/sketch-widget.min.js)
        echo "Minified size: $size bytes"
        
        # Should be less than 50KB
        if [ $size -gt 51200 ]; then
          echo "Warning: Bundle size is larger than expected"
        fi

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes
          
          See [CHANGELOG.md](CHANGELOG.md) for full details.
          
          ## CDN Usage
          
          ```html
          <script src="https://cdn.jsdelivr.net/gh/yourusername/sketch-widget@${{ github.ref }}/dist/sketch-widget.min.js"></script>
          ```
          
          ## NPM Installation
          
          ```bash
          npm install sketch-widget@${{ github.ref }}
          ```
        draft: false
        prerelease: false
    
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-jsdelivr:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Purge jsdelivr cache
      run: |
        # Purge the jsdelivr cache for the new version
        curl -X POST "https://purge.jsdelivr.net/gh/yourusername/sketch-widget@${{ github.ref }}/dist/sketch-widget.min.js"
        curl -X POST "https://purge.jsdelivr.net/gh/yourusername/sketch-widget@latest/dist/sketch-widget.min.js" 